version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bitcoin-indicator-alert-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9oqfaddn9oiy"
s3_prefix = "bitcoin-indicator-alert-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
